baseURL = 'https://dujh22.github.io/LLMDailyDigestWeb/'
languageCode = 'zh-CN'
title = 'LLM-DailyDigest'
theme = 'FixIt'

# Table Of Contents settings
[markup.tableOfContents]
  startLevel = 2
  endLevel = 10
